

export const INBOX_Activity = [
  {
    id: "msg-1",
    avatar: "./Ziva.jpg",
    sender: "Ziva Obscorp",
    subject: "Confirmed: Q3 API Roadmap & Meeting Agenda",
    timestamp: "10:42 AM",
    status: "Delivered",
    statusClass: " text-subtle ",
  },
  {
    id: "msg-2",
    avatar: "./Alex.jpg",
    sender: "Alex Lee",
    subject: "Follow-up: Product walkthrough and pricing notes",
    timestamp: "09:15 AM",
    status: "Delivered",
    statusClass: "text-subtle ",
  },
  {
    id: "msg-3",
    avatar: "./Rohan.jpg",
    sender: "Rohan Lobo",
    subject: "Design partnership proposal for launch week",
    timestamp: "Yesterday",
    status: "Pending",
    statusClass: "text-subtle",
  },
  {
    id: "msg-4",
    avatar: "./Adam.jpg",
    sender: "Adam Wise",
    subject: "Workspace migration checklist and next steps",
    timestamp: "Aug 21",
    status: "Delivered",
    statusClass: "text-subtle  ",
  },
  {
    id: "msg-5",
    avatar: "./vivek.jpg",
    sender: "Vivek Nagarkoti",
    subject: "Sprint handoff summary for engineering team",
    timestamp: "Aug 20",
    status: "Pending",
    statusClass: "text-subtle ",
  },
  {
    id: "msg-6",
    avatar: "./Malik.jpg",
    sender: "Malik James",
    subject: "Deployment window confirmation for Friday",
    timestamp: "Aug 19",
    status: "Failed",
    statusClass: "text-subtle ",
  },
  {
    id: "msg-7",
    avatar: "./Jack.jpg",
    sender: "Jack Sparrow",
    subject: "Team invite flow feedback and review notes",
    timestamp: "Aug 18",
    status: "Delivered",
    statusClass: "text-subtle ",
  },
  {
    id: "msg-8",
    avatar: "./Sarah.jpg",
    sender: "Sarah Abdullah",
    subject: "Campaign sync: lifecycle email updates",
    timestamp: "Aug 17",
    status: "Failed",
    statusClass: "text-subtle ",
  },
  {
    id: "msg-9",
    avatar: "./Natasha.jpg",
    sender: "Natasha Stankovic",
    subject: "Creative review request for onboarding sequence",
    timestamp: "Aug 17",
    status: "Delivered",
    statusClass: "text-subtle ",
  },
  {
    id: "msg-10",
    avatar: "./Kristina.jpg",
    sender: "Kristina Oliver",
    subject: "Database access confirmation and setup guide",
    timestamp: "Aug 17",
    status: "Failed",
    statusClass: "text-subtle ",
  },
];